[project]
name = "l1-learning-supabase-and-streamlit-cloud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.41.1",
    "supabase>=2.11.0",
]
